site_name: MK Chong
extra_css:
    - stylesheets/extra.css
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - toc.integrate
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    
  language: en
  palette:
    - scheme: youtube
      primary: white
      accent: green
  icon:
    admonition:
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - blog:
      blog_dir: ./blog
      blog_toc: true


extra:
  generator: false
  # social:
  #   - icon: fontawesome/brands/github-alt
  #     link: https://github.com
  #   - icon: fontawesome/brands/x-twitter
  #     link: https://twitter.com
  #   - icon: fontawesome/brands/linkedin
  #     link: https://www.linkedin.com

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com"  target="_blank" rel="noopener">MK Chong</a>